### ISSUE TITLE
华为nexus 6P 闪退 Xposed install 已经激活 且 xmonkey 模块已授权激活 但是打开还是闪退

### ISSUE THREAD

**Issue by lidongdabie** [zhangzhao4444/XMonkey#1]

**Comment by lidongdabie** [comment]
03-05 17:00:22.861  4959  4959 E AndroidRuntime: java.lang.RuntimeException: Unable to create service tv.panda.test.xmonkey.services.TestService: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
03-05 17:00:22.861  4959  4959 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3202)
03-05 17:00:22.861  4959  4959 E AndroidRuntime: 	at android.app.ActivityThread.-wrap5(ActivityThread.java)
03-05 17:00:22.861  4959  4959 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1568)
03-05 17:00:22.861  4959  4959 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-05 17:00:22.861  4959  4959 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
03-05 17:00:22.861  4959  4959 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6121)
03-05 17:00:22.861  4959  4959 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-05 17:00:22.861  4959  4959 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
03-05 17:00:22.861  4959  4959 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
03-05 17:00:22.861  4959  4959 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
03-05 17:00:22.861  4959  4959 E AndroidRuntime: Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
03-05 17:00:22.861  4959  4959 E AndroidRuntime: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:679)
03-05 17:00:22.861  4959  4959 E AndroidRuntime: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
03-05 17:00:22.861  4959  4959 E AndroidRuntime: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
03-05 17:00:22.861  4959  4959 E AndroidRuntime: 	at tv.panda.test.xmonkey.ui.FloatWindow.show(FloatWindow.kt:228)
03-05 17:00:22.861  4959  4959 E AndroidRuntime: 	at tv.panda.test.xmonkey.services.TestService.show(TestService.kt:122)
03-05 17:00:22.861  4959  4959 E AndroidRuntime: 	at tv.panda.test.xmonkey.services.TestService.onCreate(TestService.kt:74)
03-05 17:00:22.861  4959  4959 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3192)
03-05 17:00:22.861  4959  4959 E AndroidRuntime: 	... 9 more
03-05 17:00:22.864  2721  3609 W ActivityManager:   Force finishing activity tv.panda.test.xmonkey/.ui.SettinigsActivity
03-05 17:00:22.929  4959  4964 I art     : Do partial code cache collection, code=26KB, data=24KB
03-05 17:00:22.930  4959  4964 I art     : After code cache collection, code=26KB, data=24KB
03-05 17:00:22.930  4959  4964 I art     : Increasing code cache capacity to 128KB
03-05 17:00:22.934  4959  4964 I art     : Compiler allocated 7MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
03-05 17:00:22.945  4280  4556 W GCoreFlp: No location to return for getLastLocation()
03-05 17:00:22.945  4280  4648 W FusedLocationProvider: location=null
03-05 17:00:22.948  2721  4803 I Adreno  : QUALCOMM build                   : 6818200, Idb2b4cb785
03-05 17:00:22.948  2721  4803 I Adreno  : Build Date                       : 11/18/16
03-05 17:00:22.948  2721  4803 I Adreno  : OpenGL ES Shader Compiler Version: XE031.09.00.04
03-05 17:00:22.948  2721  4803 I Adreno  : Local Branch                     : N25
03-05 17:00:22.948  2721  4803 I Adreno  : Remote Branch                    : 
03-05 17:00:22.948  2721  4803 I Adreno  : Remote Branch                    : 
03-05 17:00:22.948  2721  4803 I Adreno  : Reconstruct Branch               : 
03-05 17:00:22.956  2721  4803 I OpenGLRenderer: Initialized EGL, version 1.4
03-05 17:00:22.957  2721  4803 D OpenGLRenderer: Swap behavior 1

**Comment by lidongdabie** [comment]
操作系统 安卓 7.1.2 angler-03.81
